## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the alias `pd`.

In [1]:
import pandas as pd 

**2.** Print the version of pandas that has been imported.

In [2]:
print(pd.__version__)

2.2.0


**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [ ]:
#print out all version info of pandas
print(pd.show_versions(as_json=False))



INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.13.5
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26100
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.2.3
numpy                 : 2.1.3
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 25.1
Cython                : None
sphinx                : 8.2.3
IPython               : 8.30.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.2
html5lib   

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [93]:
import pandas as pd 
import numpy as np 
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
data_1 = pd.DataFrame(data,labels)

print(data_1)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [23]:
print(data_1.describe())


            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000


**6.** Return the first 3 rows of the DataFrame `df`.

In [26]:
data_1.head(3)


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [32]:
# Select just the 'animal' and 'age' columns from the DataFrame `df
df= data_1[['animal', 'age']]
df.head(3)

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [37]:
# Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`

print(df.iloc[[3, 4, 8], [0, 1]])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0


**9.** Select only the rows where the number of visits is greater than 3.

In [40]:
# **9.** Select only the rows where the number of visits is greater than 3.
print(data_1[data_1['visits'] > 3])


Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []


**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [46]:
print(data_1[data_1['age'].isnull()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [47]:
print(data_1[(data_1['animal'] == 'cat') & (data_1['age'] < 3)])


  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


**12.** Select the rows the age is between 2 and 4 (inclusive).

In [49]:
print(data_1[(data_1['age'] >2 ) & (data_1['age'] < 4)])


  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no


**13.** Change the age in row 'f' to 1.5.

In [52]:
data_1.iloc[[5],[1]] = 1.5
print(data_1)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [55]:
print(data_1["visits"].sum())

19


**15.** Calculate the mean age for each different animal in `df`.

In [56]:
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [58]:
# Append new row 'k'
data_1.loc['k'] = ['rabbit', 2.0, 1, 'no']
print(data_1)


   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c   snake  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g   snake  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no
k  rabbit  2.0       1       no


**17.** Count the number of each type of animal in `df`.

In [59]:
print(data_1["animal"].value_counts())

animal
cat       4
dog       4
snake     2
rabbit    1
Name: count, dtype: int64


**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [88]:
dt= data_1.sort_values(by=['age','visits'] ,ascending=[False,True])
dt


animal  age  visits priority
i     dog  7.0       2      NaN
e     dog  5.0       2      NaN
g   snake  4.5       1      NaN
j     dog  3.0       1      NaN
b     cat  3.0       3      NaN
a     cat  2.5       1      NaN
k  rabbit  2.0       1      NaN
f     cat  1.5       3      NaN
c   snake  0.5       2      NaN
h     cat  NaN       1      NaN
d     dog  NaN       3      NaN

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [94]:
data_1['priority'] = data_1['priority'].str.lower().map({'yes': True, 'no': False})
print(data_1)

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False


**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [95]:
dt1 = dt['animal'].replace('snake', 'python')
print(dt1)

i       dog
e       dog
g    python
j       dog
b       cat
a       cat
k    rabbit
f       cat
c    python
h       cat
d       dog
Name: animal, dtype: object


**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [96]:
print(data_1.pivot_table(values='age', index='animal', columns='visits', aggfunc='mean'))

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
snake   4.5  0.5  NaN


## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [1]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

# Keep rows where the current value is not equal to the previous one
filtered_df = df[df['A'] != df['A'].shift()]

print(filtered_df)


   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7


**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [2]:
import numpy as np

df = pd.DataFrame(np.random.random(size=(5, 3)))  # 5x3 DataFrame of floats
df_row_centered = df.sub(df.mean(axis=1), axis=0)
print(df_row_centered)


          0         1         2
0  0.524305 -0.195405 -0.328900
1  0.111995 -0.191674  0.079679
2 -0.086995 -0.332055  0.419050
3  0.134754  0.342846 -0.477599
4  0.084917 -0.265529  0.180613


**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [4]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
#column with the smallest sum
min_col_label = df.sum().idxmin()
print("Column with smallest sum:", min_col_label)


Column with smallest sum: a


**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [3]:
import numpy as np

df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
unique_row_count = df.drop_duplicates().shape[0]
unique_row_count_alt = df.nunique(axis=0)
print("Number of unique rows:", unique_row_count)


Number of unique rows: 7


The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [5]:
import pandas as pd

df = pd.DataFrame({
    'grps': list('aaabbcaabcccbbc'), 
    'vals': [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87]
})
result = (df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum()).sort_index())

print(result)


grps
a    409
b    156
c    345
Name: vals, dtype: int64


**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). 

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [8]:
import pandas as pd
import numpy as np

# Create sample DataFrame
np.random.seed(0)
df = pd.DataFrame({
    'A': np.random.randint(1, 101, size=100),
    'B': np.random.randint(1, 101, size=100)
})

# Bin the 'A' values into intervals of 10
bins = pd.cut(df['A'], bins=np.arange(0, 101, 10))
# Group by bins and sum 'B'
result = df.groupby(bins)['B'].sum()

print(result)



A
(0, 10]      581
(10, 20]     586
(20, 30]     447
(30, 40]     563
(40, 50]     523
(50, 60]     275
(60, 70]     616
(70, 80]     373
(80, 90]     806
(90, 100]    237
Name: B, dtype: int32


C:\Users\ghula\AppData\Local\Temp\ipykernel_5924\1392563496.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(bins)['B'].sum()


## DataFrames: harder problems 

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be 

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [10]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
last_zero_index = -1
y = []
for i, val in enumerate(df['X']):
    if val == 0:
        last_zero_index = i
        y.append(0)
    else:
        y.append(i - last_zero_index)
df['Y'] = y

print(df)


   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2


**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data. 

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [12]:
import pandas as pd
import numpy as np

np.random.seed(0)
df = pd.DataFrame(np.random.randint(0, 100, size=(10, 10)))

flat = df.to_numpy().flatten()
# print("Flattened DataFrame:", flat)
top_indices = np.argpartition(-flat, 3)[:3] 
# print("Top 3 flat indices:", top_indices)
row_col_indices = [np.unravel_index(idx, df.shape) for idx in top_indices]
# print("Row and column indices of top 3 values:", row_col_indices)
row_col_indices = sorted(row_col_indices, key=lambda x: df.iat[x[0], x[1]], reverse=True)
print("Top 3 value positions:", row_col_indices)


Top 3 value positions: [(np.int64(3), np.int64(3)), (np.int64(7), np.int64(7)), (np.int64(9), np.int64(3))]


**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [ ]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
# print(df.head())
group_means = df[df['vals'] >= 0].groupby('grps')['vals'].mean()
print("Group means for non-negative values:", group_means)
df['group_mean'] = df['grps'].map(group_means)
df['patched_vals'] = np.where(df['vals'] < 0, df['group_mean'], df['vals'])
# df.drop(columns='group_mean', inplace=True)
print(df)


Group means for non-negative values: grps
A    13.6
B    28.0
Name: vals, dtype: float64
    vals grps  group_mean  patched_vals
0    -12    A        13.6          13.6
1     -7    B        28.0          28.0
2    -14    A        13.6          13.6
3      4    A        13.6           4.0
4     -7    A        13.6          13.6
5     28    B        28.0          28.0
6     -2    A        13.6          13.6
7     -1    A        13.6          13.6
8      8    A        13.6           8.0
9     -2    B        28.0          28.0
10    28    A        13.6          28.0
11    12    A        13.6          12.0
12    16    A        13.6          16.0
13   -24    A        13.6          13.6
14   -12    A        13.6          13.6


**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.


**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [21]:
dates = pd.date_range(start='2015-01-01', end='2015-12-31', freq='B')
# print(dates)
s = pd.Series(np.random.randn(len(dates)), index=dates)
print(s.head())

2015-01-01    0.367036
2015-01-02    0.332867
2015-01-05   -0.495868
2015-01-06    0.094114
2015-01-07    0.382038
Freq: B, dtype: float64


**34.** Find the sum of the values in `s` for every Wednesday.

In [22]:
wednesday_sum = s[s.index.weekday == 2].sum()

print(wednesday_sum)

-6.4292340311833565


**35.** For each calendar month in `s`, find the mean of values.

In [25]:
s_m = s.resample('M').mean()
print(s_m)

2015-01-31   -0.320316
2015-02-28   -0.327700
2015-03-31   -0.081153
2015-04-30    0.001709
2015-05-31   -0.136828
2015-06-30    0.159227
2015-07-31    0.167819
2015-08-31    0.209246
2015-09-30   -0.197130
2015-10-31    0.324326
2015-11-30    0.080088
2015-12-31   -0.171762
Freq: ME, dtype: float64


C:\Users\ghula\AppData\Local\Temp\ipykernel_5924\1587326896.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  s_m = s.resample('M').mean()


**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [30]:
month_groups = (s.index.to_period('M').month - 1) // 4 + 1
print(month_groups)
result = s.groupby(month_groups).idxmax()
print(result)


Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       ...
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      dtype='int64', length=261)
1   2015-04-24
2   2015-07-22
3   2015-10-14
dtype: datetime64[ns]


**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)


**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [32]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)
print(df)


            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"


**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame. 

In [35]:
temp = df['From_To'].str.split('_', expand=True)
# print(temp)
temp.columns = ['From', 'To']
print(temp)


       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [36]:
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()
print(temp)


       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [37]:
df.drop(columns='From_To', inplace=True)
df = pd.concat([temp, df], axis=1)
print(df)



       From         To  FlightNumber  RecentDelays              Airline
0    London      Paris         10045      [23, 47]               KLM(!)
1    Madrid      Milan         10055            []    <Air France> (12)
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )
3  Budapest      Paris         10075          [13]       12. Air France
4  Brussels     London         10085      [67, 32]          "Swiss Air"


**42**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [38]:
# Clean 'Airline' column using regex
df['Airline'] = df['Airline'].str.replace(r'[^a-zA-Z\s]', '', regex=True).str.strip()
print(df)

       From         To  FlightNumber  RecentDelays          Airline
0    London      Paris         10045      [23, 47]              KLM
1    Madrid      Milan         10055            []       Air France
2    London  Stockholm         10065  [24, 43, 87]  British Airways
3  Budapest      Paris         10075          [13]       Air France
4  Brussels     London         10085      [67, 32]        Swiss Air


**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels. 

**44**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

In [ ]:
letters = ['A', 'B', 'C']
numbers = list(range(10))
index = pd.MultiIndex.from_product([letters, numbers], names=['letter', 'number'])
s = pd.Series(np.random.randn(len(index)), index=index)
print(s)

letter  number
A       0        -0.071025
        1        -0.240574
        2         0.007376
        3        -1.335613
        4        -0.052451
        5         0.319063
        6         1.716086
        7         1.611755
        8         0.088389
        9        -0.177068
B       0         0.733894
        1         0.867819
        2        -0.150741
        3        -1.154609
        4        -1.614361
        5        -1.453265
        6        -1.021484
        7         0.737634
        8         0.319999
        9         1.092688
C       0        -0.794358
        1         0.733720
        2         0.670218
        3         0.501350
        4        -0.456125
        5         0.040553
        6         0.922115
        7        -1.720215
        8         0.108806
        9        -0.517229
dtype: float64


In [ ]:
# Convert the second level to int


**45.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

In [52]:
s.index.is_monotonic_increasing

True

**46**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

In [53]:
s_selected = s[s.index.get_level_values('number').isin([1, 3, 6])]
print(s_selected)

letter  number
A       1         3
        3         3
        6         3
B       1         3
        3         3
        6         3
C       1         3
        3         3
        6         3
dtype: int64


**47**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

In [54]:
sliced = s.loc[pd.IndexSlice[:'B', 5:]]
sliced

letter  number
A       5         3
        6         3
        7         3
        8         3
        9         3
B       5         3
        6         3
        7         3
        8         3
        9         3
dtype: int64

**48**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

In [55]:
s_sum = s.groupby(level="letter").sum()
s_sum

letter
A    30
B    30
C    30
dtype: int64

**49**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

In [50]:
# s.groupby(s.index.get_level_values(1)).sum()

**50**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

Number  Letter
0       A         15
1       A         64
2       A         11
3       A         78
4       A         19
5       A         88
6       A         25
7       A         38
8       A         38
9       A          4
0       B         31
1       B         45
2       B         43
3       B         16
4       B         74
5       B         32
6       B          9
7       B         37
8       B          9
9       B          4
0       C         78
1       C         11
2       C         10
3       C         42
4       C         30
5       C         11
6       C         92
7       C         40
8       C         87
9       C         17
dtype: int64

## Minesweeper

### Generate the numbers for safe squares in a Minesweeper grid

Difficulty: *medium* to *hard*



In this section, we'll make a DataFrame that contains the necessary data for a game of Minesweeper: coordinates of the squares, whether the square contains a mine and the number of mines found on adjacent squares.

**51**. Let's suppose we're playing Minesweeper on a 5 by 4 grid, i.e.
```
X = 5
Y = 4
```
To begin, generate a DataFrame `df` with two columns, `'x'` and `'y'` containing every coordinate for this grid. That is, the DataFrame should start:
```
   x  y
0  0  0
1  0  1
2  0  2
```

In [ ]:
import pandas as pd
from itertools import product

X = 5
Y = 4
coordinates = list(product(range(X), range(Y)))
# print(coordinates)
df = pd.DataFrame(coordinates, columns=['x', 'y'])
print(df)


    x  y
0   0  0
1   0  1
2   0  2
3   0  3
4   1  0
5   1  1
6   1  2
7   1  3
8   2  0
9   2  1
10  2  2
11  2  3
12  3  0
13  3  1
14  3  2
15  3  3
16  4  0
17  4  1
18  4  2
19  4  3


**52**. For this DataFrame `df`, create a new column of zeros (safe) and ones (mine). The probability of a mine occuring at each location should be 0.4.

**53**. Now create a new column for this DataFrame called `'adjacent'`. This column should contain the number of mines found on adjacent squares in the grid. 

(E.g. for the first row, which is the entry for the coordinate `(0, 0)`, count how many mines are found on the coordinates `(0, 1)`, `(1, 0)` and `(1, 1)`.)

**54**. For rows of the DataFrame that contain a mine, set the value in the `'adjacent'` column to NaN.

**55**. Finally, convert the DataFrame to grid of the adjacent mine counts: columns are the `x` coordinate, rows are the `y` coordinate.

## Plotting

### Visualize trends and patterns in data

Difficulty: *medium*

To really get a good understanding of the data contained in your DataFrame, it is often essential to create plots: if you're lucky, trends and anomalies will jump right out at you. This functionality is baked into pandas and the puzzles below explore some of what's possible with the library.

**56.** Pandas is highly integrated with the plotting library matplotlib, and makes plotting DataFrames very user-friendly! Plotting in a notebook environment usually makes use of the following boilerplate:

```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
```

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to ```plt```.

```%matplotlib inline``` tells the notebook to show plots inline, instead of creating them in a separate window.  

```plt.style.use('ggplot')``` is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

For starters, make a scatter plot of this random data, but use black X's instead of the default markers. 

```df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})```

Consult the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) if you get stuck!

**57.** Columns in your DataFrame can also be used to modify colors and sizes.  Bill has been keeping track of his performance at work over time, as well as how good he was feeling that day, and whether he had a cup of coffee in the morning.  Make a plot which incorporates all four features of this DataFrame.

(Hint:  If you're having trouble seeing the plot, try multiplying the Series which you choose to represent size by 10 or more)

*The chart doesn't have to be pretty: this isn't a course in data viz!*

```
df = pd.DataFrame({"productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})
```

**58.**  What if we want to plot multiple things?  Pandas allows you to pass in a matplotlib *Axis* object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)

```
df = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })
```

**59.** Generate a day's worth of random stock data, and aggregate / reformat it so that it has hourly summaries of the opening, highest, lowest, and closing prices

**60.** Now that you have your properly-formatted data, try to plot it yourself as a candlestick chart.  Use the ```plot_candlestick(df)``` function above, or matplotlib's [```plot``` documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot.html) if you get stuck.

*More exercises to follow soon...*